### ISSUE TITLE
[PHP 7.4] Notice: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/CMRF_Abstract_Core#13]
Occurs  with PHP 7.4 in https://github.com/CiviMRF/CMRF_Abstract_Core/blob/a89b4dbc893822dc1137888e05aa2cdca1f356ee/CMRF/Core/AbstractCall.php#L176-L190 when calling `$this->getEntity()` and `$this->getAction()` while both, entity and action, are not set at this stage since the constructor does not set them.

Also, implementations are setting both, entity and action, manually later on, e.g. in https://github.com/CiviMRF/cmrf_core/blob/3737f65a0161d60fff707c30adc926dfe347ecbc/src/Call.php#L18-L27

This makes logs be flooded with those notices.

I'm not sure whether removing both lines https://github.com/CiviMRF/CMRF_Abstract_Core/blob/a89b4dbc893822dc1137888e05aa2cdca1f356ee/CMRF/Core/AbstractCall.php#L178-L179 might cause other issues, but implementations do not have a chance to retrieve both, entity and action, from the call object at this stage at all.

@jaapjansma what do you think?

**Comment by jaapjansma** [comment]
I think it is fine to remove both lines.

**Comment by jensschuppe** [comment]
Thanks @jaapjansma - I could not see any problems while testing, so merged into `master`.
