### ISSUE TITLE
cURL connectors should set call status to STATUS_FAILED when an API error occurred

### ISSUE THREAD

**Issue by jensschuppe** [CiviMRF/CMRF_Abstract_Core#7]
Calls are being logged as `STATUS_DONE` when the API returned an error (`is_error = 1`), which is contrary to how the local connector acts on API errors (catching exception and setting the call status to `STATUS_FAILED`).

This leads to API errors not being easily identifiable and kept in the CMRF call log.

Maybe there should be a different status for API errors, as `STATUS_FAILED` may denote the call itself having failed due to connection issues?

@jaapjansma @systopia Any thoughts on that?

**Comment by jaapjansma** [comment]
I don't have any objections against `STATUS_FAILED`

**Comment by jaapjansma** [comment]
I have updated the code so it returns STATUS_FAILED when is_error != 0
